### ISSUE TITLE
No messages at all

### ISSUE THREAD

**Issue by Struart88** [szpajder/dumpvdl2#10]
Hello
My problem is that i don;t get any messages (i readed FAQ).
When i start dumpvdl2 with dumpvdl2 --rtlsdr 0 --gain 19.7 --correction 23 --centerfreq 136650000 136725000 136775000 136975000 136875000
I use  --gain 19.7 because my Lifeview LV5TDeluxe Fitipower FC0013 tuner cannot go more

It either find maybe 4 msgs or none at all after 20 min.

When i use on same devices vdlm2dec i get bunch of msgs just from the start.
Testedd 1.6.0 and 1.7.0

Whats going on?

**Comment by szpajder** [comment]
How can I know this? Every setup and every location is different.

Maybe the gain is too low? (19.7 is quite low, I think)

Maybe you have interference?

Try rebuilding the program with -DCMAKE_BUILD_TYPE=Debug to enable
debugging output on standard error. It will tell you if it attempts to
decode any frames at all and at which stage the decoding fails.

**Comment by Struart88** [comment]
Ok problem solved.
Thats not a problem with gain.

Problem was with correction value.
I give correction 18 when it should be -18.

Stupid mistake sorry for bother.
