### ISSUE TITLE
No decoded data.

### ISSUE THREAD

**Issue by thebaldgeek** [szpajder/dumpvdl2#17]
vdlm2dec and acarsdec both work Ok (thousands of messages per day) so I am confident that the antenna and RTLSDRv3 dongle are working correctly.    

Built on a Pi 3 with the lite OS version.
Did an apt-get update and apt-get upgrade before starting the build.
No other ADSB etc software installed. Just 1 USB SDR dongle installed.
    
I carefully followed the instructions on the github page:
1. git clone git://git.osmocom.org/rtl-sdr.git
2. cd rtl-sdr/
3. mkdir build
4. cd build
5. cmake ../
6. make
7. sudo make install
8. sudo ldconfig
9. sudo apt install build-essential cmake git libglib2.0-dev pkg-config
10. sudo echo "blacklist dvb_usb_rtl28xxu" >> /etc/modprobe.d/blacklist.conf`
11.  Rebooted the Pi.
12. git clone https://github.com/szpajder/libacars
13. cd libacars
14. mkdir build
15. cd build
16.  cmake -DMIRISDR=FALSE -DSDRPLAY=FALSE -DSOAPYSDR=FALSE -DSQLITE=FALSE -DETSY_STATSD=FALSE -DRAW_BINARY_FORMAT=FALSE -DZMQ=FALSE ../
17. make
18.  sudo make install
19. dumpvdl2 --rtlsdr -0 --gain 42 --correction 7 136.725 136.775 136.800 136.975

dumpvdl2 2.1.0 (libacars 2.1.3)
Sampling rate set to 1050000 sps
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Exact sample rate is: 1050000.026077 Hz
[R82XX] PLL not locked!
[R82XX] PLL not locked!
Center frequency set to 136 Hz
[R82XX] PLL not locked!
Device #0: gain set to 42.10 dB
Device 0 started
Allocating 15 zero-copy buffers

After running for 2+ hours, there is no output. With vdlm2dec I see output within 15-20 seconds during the day.
I prefer the decoded text output rather than JSON and have dumpvdl2 running Ok from 2-3 years ago, just the newer version is not showing any output.

Thanks for your help.

**Comment by szpajder** [comment]
>
>
>    1. git clone https://github.com/szpajder/libacars
>    2. cd libacars
>    3. mkdir build
>    4. cd build
>    5. cmake -DMIRISDR=FALSE -DSDRPLAY=FALSE -DSOAPYSDR=FALSE
>    -DSQLITE=FALSE -DETSY_STATSD=FALSE -DRAW_BINARY_FORMAT=FALSE -DZMQ=FALSE ../
>    6. make
>    7. sudo make install
>
>
So you have built and installed libacars (giving it plenty of -D options
which it does not care about, since they all apply to dumpvdl2 rather than
libacars), but have you actually built dumpvdl2?


>
>    1. dumpvdl2 --rtlsdr -0 --gain 42 --correction 7 136.725 136.775
>    136.800 136.975
>
> dumpvdl2 2.1.0 (libacars 2.1.3)
>
OK, it shows version 2.1.0, so let's assume that you've built it at some
point. But this is not how you pass channel frequencies to it. Check out
the help text:

common options:
    <freq_1> [<freq_2> [...]]                   VDL2 channel frequencies, *in
Hz*

**Comment by thebaldgeek** [comment]
I am an idiot. I need to carefully and _fully_ RTFM
Thank-you
Frequency in Hz and getting output.
