### ISSUE TITLE
libzmq version checking error

### ISSUE THREAD

**Issue by philharrisathome** [szpajder/dumpvdl2#18]
After adding ZMQ support to dumpvdl2 I get the following error in my environment, incorrectly stating that libzmq 4.0.5 is **older** than 3.2.0:

```
pi@wx-rx:~/vdl2 $ dumpvdl2 --output decoded:json:zmq:mode=server,endpoint=tcp://*:5555
dumpvdl2 2.1.0 (libacars 2.1.3)
output_zmq: error: libzmq library version 4.0.5 is too old; at least 3.2.0 is required
Invalid output configuration
```

This is caused by problematic version checking code from line 51 of output_zmq.c, which causes the error during the minor check (0<2).

```
	if(major < LIBZMQ_VER_MAJOR_MIN || minor < LIBZMQ_VER_MINOR_MIN || patch < LIBZMQ_VER_PATCH_MIN) {
		fprintf(stderr, "output_zmq: error: libzmq library version %d.%d.%d is too old; at least %d.%d.%d is required\n",
				major, minor, patch,
				LIBZMQ_VER_MAJOR_MIN, LIBZMQ_VER_MINOR_MIN, LIBZMQ_VER_PATCH_MIN);
		goto fail;
	}
```

One possible way to fix this is:

`	if((major*1000000 + minor*1000 + patch) < (LIBZMQ_VER_MAJOR_MIN*1000000 + LIBZMQ_VER_MINOR_MIN*1000 + patch)) {`

which passes the check successfully:

```
pi@wx-rx:~/vdl2 $ dumpvdl2 --output decoded:json:zmq:mode=server,endpoint=tcp://*:5555
dumpvdl2 2.1.0-dirty (libacars 2.1.3)
No input specified
Use --help for help
```

Build environment is Raspberry Pi 3 Model B Rev 1.2, Linux wx-rx 4.19.40-v7+ #1217 SMP Tue May 7 17:22:08 BST 2019 armv7l GNU/Linux

Thanks for the great work on dumpvdl2! Apart from this minor problem configuration for a remote monitoring station was very smooth.

**Comment by szpajder** [comment]
Thanks for pointing this out! I pushed a fix to the `unstable` branch. I'll make a new release later this week.

**Comment by philharrisathome** [comment]
:+1:
