### ISSUE TITLE
Airspy Usage

### ISSUE THREAD

**Issue by alphafox02** [szpajder/dumpvdl2#22]
Just occurred to me after reading your front page that there’s probably no way to currently use an Airspy R2? I’m thinking it’s the sample rate warning you mention. I don’t suppose this has been changed in the current release?

**Comment by szpajder** [comment]
Correct. Nothing has changed recently on this matter.

**Comment by alphafox02** [comment]
Thank you for the confirmation. I’ll hurry up and send out an rtlsdr or rsp1a to the person testing this.
