### ISSUE TITLE
Information about cpdlc

### ISSUE THREAD

**Issue by Lissen2me** [szpajder/dumpvdl2#3]
Good afternoon. I'm doing a project to decode Inmarsat Aero messages. A number of messages I can not decode, but your module decpdlc can. It is possible to compile .dll for visual studio c # or advise the source of information to decode such messages, could not find it. Thank you in advance.

**Comment by szpajder** [comment]
My plan is to move FANS-1/A and ADS-C decoder code out of dumpvdl2 into a
separate project (library) which could be used by other software projects
dealing with ACARS messages. But it's all TODO and I can't give you any
more precise ETA than "maybe this year, maybe next".

I assume that you can already decode ASN.1 and PER, correct? If so, then
refer to asn1/fans-cpdlc.asn1 file in the dumpvdl2 source tree - this is
the complete formal specification of all messages and data types used in
FANS-1/A CPDLC. This is what CPDLC decoder used by dumpvdl2 and decpdlc has
been built from.

**Comment by Lissen2me** [comment]
Thank you, I will try. If you get something, I'll send you c# code.

**Comment by szpajder** [comment]
The library is now available here: https://github.com/szpajder/libacars . It provides decoders for ADS-C and FANS-1/A CPDLC. There is a stable release 1.0.0 now available, together with a binary package for 64-bit Windows.

We already have first adopters of this project:

- dumpvdl2 - the latest code in unstable branch uses libacars for all tasks related to ACARS decoding; the library is a mandatory dependency.

- Thierry Leconte's acarsdec and vdlm2dec use libacars optionally (if installed) to decode ATS applications

- Support for ATS applications decoding with libacars is now in the master branch of Jonty's JAERO Inmarsat decoder and will be available in the next stable release of the program.
