### ISSUE TITLE
Output to network may fail on startup

### ISSUE THREAD

**Issue by varnav** [szpajder/dumpvdl2#32]
Hello!

I dump to network using this parameter:

`--output decoded:text:udp:address=myhost.net,port=1111`

On startup of my Orange Pi dumpvdl seems to start before Pi is connected to WiFi. Because of this it starts dumpvdl2 normally but there is zero networking traffic. I have to fix it manually by restarting the service.

Possible solution is to change lines at 

https://github.com/szpajder/dumpvdl2/blob/f671d9ecf8d4fc60190c097daaad5df9404622b2/etc/dumpvdl2.service

from

```
Wants=network.target
After=network.target
```

to

```
Wants=network-online.target
After=network-online.target
```

Difference is described in detail here: https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/

**Comment by szpajder** [comment]
Thanks, correction pushed to unstable branch.
