### ISSUE TITLE
Adding standard input support

### ISSUE THREAD

**Issue by luarvique** [szpajder/dumpvdl2#35]
This came up as I was trying to integrate dumpvdl2 support into OpenWebRX:

Will it be possible to add support for standard input, same as in dumphfdl? If yes, what would be the minimal input bandwidth required?

**Comment by szpajder** [comment]
In theory it's possible, however its use would be quite limited, since the
demodulator currently works on a rate of 10 samples per symbol (ie. 105000
samples per second) and it only accepts integer multiples of this sampling
rate. I haven't tested it with multipliers lower than 10 (that is 1050000
sps).

**Comment by luarvique** [comment]
Getting 210ksps out of OWRX is pretty realistic. I can probably get 315ksps out of it, although the code is struggling at such rates (there are some pieces there written in Python). So, it might be worth a try, if DumpVDL2 can do its job at 2-3 samples per symbol.

Another, related topic I wanted to ask about is whether you can add standard input option to your AcarsDec tool. That one does not require high input sampling rates, does it? A lot of people appear to be interested in ACARS decoding, more than in VDL2 in fact.

**Comment by szpajder** [comment]
> So, it might be worth a try, if DumpVDL2 can do its job at 2-3 samples per symbol.

It can't. It needs to estimate tx clock frequency offset pretty quickly using only the frame preamble, which is very short. The more samples per second, the better the offset estimate. In fact, I'd prefer to increase the SPS even more.

> Another, related topic I wanted to ask about is whether you can add standard input option to your AcarsDec tool.

It's not my tool, please ask here: https://github.com/TLeconte/acarsdec

**Comment by luarvique** [comment]
Acknowledged.

**Comment by luarvique** [comment]
I've almost abandoned all hope, but now looks like I can realistically get 1.05Msps IQ stream out of the OpenWebRX and into the DumpVDL2. Tomasz, could you please consider adding the STDIN support, by supplying "-" as the input file name? Please?

**Comment by szpajder** [comment]
Implemented now in unstable branch.

**Comment by luarvique** [comment]
Thanks! Trying to integrate with OWRX now...

**Comment by luarvique** [comment]
It's alive! IT'S ALIVE!
![image](https://github.com/szpajder/dumpvdl2/assets/3293202/953a982f-416c-4a34-a3ed-873451a448dc)

**Comment by luarvique** [comment]
Experiments show that oversampling rate of x2 (210000) is enough for DumpVDL2 to work. The input stream is prefiltered to 25kHz. Please, let me know if you smell any fudge in this statement.
