### ISSUE TITLE
duplicate in statsd.c

### ISSUE THREAD

**Issue by dziban303** [szpajder/dumpvdl2#36]
Hi, I have absolutely no idea what I'm doing but I did notice a duplicated line in `statsd.c` at lines [48-49](https://github.com/szpajder/dumpvdl2/blob/9b91adff7eccf98eab12fa2f6390d2e3f99c4ccf/src/statsd.c#L48-L49) which both declare `"decoder.errors.bitstream",`

I don't know if this is intentional or if it's had any downstream effects, good or bad, at all, but thought you might want to know.

Ta

P.S. Happy new year

**Comment by szpajder** [comment]
Indeed, it shouldn't be there. It's harmless (it just causes this counter
to be initialized twice on startup), but I removed it anyway. Fix pushed
into unstable branch. Thanks for pointing this out.
