### ISSUE TITLE
command line parsing of invalid characters causes weird errors

### ISSUE THREAD

**Issue by f00b4r0** [szpajder/dumpvdl2#44]
I don't know if this really qualifies as an issue, but I botched the command line by introducing utf-8 characters that looked like space and dashes, and that caused dumpvdl2 to start sending some (but not all) statsd reports with a 0 frequency value.

The offending characters were:
```
e2 80 93 2d 75 74 63 20 2d 2d 6f 75 74 70 75 74  |...-utc --output|
```

which showed on the terminal like space followed by `--utc`.

The argument immediately before was the station id, so I suspect that the invalid chars where mangled into the station-id, maybe clobbering the frequency value during statsd output formatting? No idea really, I haven't looked that far.

I'm not sure this should cause the program to misbehave as it did though, so I'm reporting this here. Meanwhile I noticed another problem in the code which I'll address in a PR.

HTH

**Comment by szpajder** [comment]
Thanks, it's now fixed in unstable branch. As a bonus, frequencies might now be specified in Hz, kHz, MHz or GHz (as floats or integers with an optional [kKmMgG] suffix).

**Comment by f00b4r0** [comment]
Confirmed fixed:

```
dumpvdl2 2.3.0-54ff5de (libacars 2.2.0)
Cannot parse '–-utc' as frequency: not a valid floating-point number
```

It's not immediately obvious from your change *why* this is fixed, but it is :-)

**Comment by szpajder** [comment]
These weird characters were treated as an optionless argument which
dumpvdl2 expects to be the channel frequency to decode. So it tried to
convert it to a number using strtoul() and failed, however no error
checking was in place, so the result of this operation was 0 - and this was
the channel frequency to be decoded and reported via statsd. So I replaced
it with a function which performs a proper validation and additionally
supports the new (hopefully more convenient) syntax.

**Comment by f00b4r0** [comment]
makes sense, thanks for the explanation!
