### ISSUE TITLE
Request: Full streaming data

### ISSUE THREAD

**Issue by thebaldgeek** [szpajder/dumpvdl2#8]
Glad to read that full JSON data is being considered.... But, I would like to ask about including all the information that you currently have be included in the streamed data.

For example, this is what shows in the terminal when running;
[2019-02-03 20:43:41 UTC] [136.650] [-19.6/-34.8 dBFS] [15.2 dB] [2.7 ppm]
A2AB41 (Aircraft, Airborne) -> 11208A (Ground station): Response
AVLC: type: S (Receive Ready) P/F: 0 rseq: 4

But only this latter part is streamed when using the option --output-acars-pp.
A2AB41 (Aircraft, Airborne) -> 11208A (Ground station): Response
AVLC: type: S (Receive Ready) P/F: 0 rseq: 4

I would find the date, time, frequency and signal strength of huge value in my website.
Seems strange to me that it is clearly shown but not streamed.
Perhaps I have a setting wrong?

**Comment by thebaldgeek** [comment]
Also do you filter out aircraft and ground station HEX codes? I never see them at all.

**Comment by szpajder** [comment]
--output-acars-pp is meant for interaction with Planeplotter program, so the stream contents and format must be understandable by it. I can't change the format freely.

Once the JSON streaming is implemented, it will include all data.

**Comment by thebaldgeek** [comment]
Understood, I figured that was the case, but dropping the -pp does not add anything, in fact it seems to be the same?
I guess my question is, is there a streaming option, even an undocumented debug one that includes everything?

**Comment by thebaldgeek** [comment]
Just FYI for anyone else that might be looking for a work around until we get the JSON output....
You can pipe the terminal output to netcat and get the full info via a stream.
eg; dumpvdl2 --rtlsdr 2 --gain 44.5 136650000 136800000 136975000 | nc -u URL.com 12345
This will stream via udp to url.com port 12345
I am now getting frequency and signal strength data into my word filter for further analysis.

**Comment by szpajder** [comment]
@thebaldgeek the feature you've requested is now available for testing in unstable branch.

**Comment by szpajder** [comment]
Released in v2.0.0.

Closing.
